version: '3'

networks:
  web:
    external: true

services: 

  traefik:
    container_name: jamieowen_traefik
    image: traefik:latest
    restart: always
    command: --api
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/acme
      - ./traefik/traefik.toml:/traefik.toml
    networks:
      - web
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:admin.localhost,admin.jamieowen.com
      - traefik.frontend.rule=PathPrefixStrip:/proxy
      

    
