version: '3'

networks:
  web:
    external: true

services: 
  traefik:
    image: traefik:latest
    restart: always
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    networks:
      - web
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:admin.localhost,admin.jamieowen.com
      - traefik.frontend.rule=PathPrefixStrip:/proxy
  jamieowen.com: 
    image: jamieowen.com:latest
    restart: always
    networks:
      - web    
    labels:
      - traefik.port=3000
      - traefik.frontend.rule=Host:docker.localhost,localhost,jamieowen.com,www.jamieowen.com
  labs.jamieowen.com: 
    image: labs.jamieowen.com:latest
    restart: always
    networks:
      - web    
    labels:
      - traefik.port=80
      - traefik.frontend.rule=Host:labs.localhost,labs.jamieowen.com
      

    