version: '3'

networks:
  web:
    external: true

services: 

  traefik:
    container_name: jamieowen_traefik
    image: traefik:v1.7
    restart: always
    #command: --api --docker
    domainname: jamieowen.com
    environment: 
      - DO_AUTH_TOKEN=2a4bc437228bd27fa8d902683de22c7cb333eae290772334123191d544f35e26
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/acme
      - ./traefik.toml:/traefik.toml
    networks:
      - web
    labels:
      - traefik.port=8080      
      - traefik.docker.network=web
      - traefik.frontend.entryPoints="http,https"
      - traefik.frontend.rule=Host:admin.localhost,admin.jamieowen.com
      - traefik.frontend.rule=PathPrefixStrip:/proxy
      

    
