debug = true

#logLevel DEBUG, INFO, WARN, ERROR, FATAL, PANIC
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
exposedByDefault = false
endpoint = "unix:///var/run/docker.sock"
domain = "jamieowen.com"
watch = true

[acme]
email = "hello@jamieowen.com"
storage = "acme/certs.json"
acmeLogging=true
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"