debug = true


# FUCK, FUCK, FUCK, FUCK, FUCK, FUCK, FUCK ME.
# THE MOST PAIN IN THE ARSE FUCKING BULLSHIT TO FIND A CENTRAL SOURCE OF TRUTH ON.
# TOML FORMAT IS ALL OVER THE PLACE, TRAFEIK DOCS ARE SHITE, ETC, ETC, 
# I DON'T KNOW IF NO DOCUMENTATION IS WORSE THAN BAD DOCUMENTATION.

# Here's some rnadom urls ;
# https://www.reddit.com/r/selfhosted/comments/d5mbd6/traefik_issue_field_not_found/

#logLevel DEBUG, INFO, WARN, ERROR, FATAL, PANIC
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[api]

# https://docs.traefik.io/providers/docker/
[docker]
exposedByDefault = false
endpoint = "unix:///var/run/docker.sock"
#domain = "jamieowen.com"
watch = true

# [acme]
# email = "hello@jamieowen.com"
# storage = "acme/certs.json"
# entryPoint = "https"
# acmeLogging=true
# onDemand = false
# [acme.dnsChallenge]
# provider = "digitalocean"
# delayBeforeCheck = 0
# [[acme.domains]]
# main = "*.jamieowen.com"
# [[acme.domains]]
# main = "jamieowen.com"